# Generated by Django 3.1.1 on 2024-11-19 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'Ingredients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('instruction_id', models.AutoField(primary_key=True, serialize=False)),
                ('step_number', models.IntegerField(blank=True, null=True)),
                ('instruction_text', models.TextField()),
            ],
            options={
                'db_table': 'Instructions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
            ],
            options={
                'db_table': 'Recipes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'Tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recipeingredients',
            fields=[
                ('recipe', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='recipe_ingredients', serialize=False, to='recipes.recipes')),
                ('amount', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'RecipeIngredients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recipetags',
            fields=[
                ('recipe', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='recipe_tags', serialize=False, to='recipes.recipes')),
            ],
            options={
                'db_table': 'RecipeTags',
                'managed': False,
            },
        ),
    ]
