# Generated by Django 5.1.2 on 2024-11-09 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('ingredient_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient_name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'Ingredients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('instruction_id', models.AutoField(primary_key=True, serialize=False)),
                ('step_number', models.IntegerField(blank=True, null=True)),
                ('instruction_text', models.TextField()),
            ],
            options={
                'db_table': 'Instructions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
            ],
            options={
                'db_table': 'Recipes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'Tags',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='instruction',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipetag',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='recipetag',
            name='tag',
        ),
        migrations.CreateModel(
            name='Recipeingredients',
            fields=[
                ('recipe', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='recipe_ingredients', serialize=False, to='recipes.recipes')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'RecipeIngredients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recipetags',
            fields=[
                ('recipe', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='recipe_tags', serialize=False, to='recipes.recipes')),
            ],
            options={
                'db_table': 'RecipeTags',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Instruction',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='RecipeIngredient',
        ),
        migrations.DeleteModel(
            name='RecipeTag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
